### PR TITLE
Add async publish endpoint

### PR DESCRIPTION
**Pull request by tylertreat**

### CODE REVIEW

**Comment by LaPetiteSouris** [comment]
Hi

It seems after `PublishAsync` is added :

```golang

rpc PublishAsync(stream PublishRequest) returns (stream PublishResponse) {}

``` 
On the [server side](https://github.com/liftbridge-io/liftbridge/blob/master/server/api.go), this rpc endpoint is not yet implemented.

Thus, if `liftbrige` master branch changes to use the latest api commit, tests will fail

```

/*/liftbridge/server/server.go:378:32: cannot use &apiServer literal (type *apiServer) as type "github.com/liftbridge-io/liftbridge-api/go".APIServer in argument to "github.com/liftbridge-io/liftbridge-api/go".RegisterAPIServer:
	*apiServer does not implement "github.com/liftbridge-io/liftbridge-api/go".APIServer (missing PublishAsync method)
```

This is also true for `go-liftbridge`, in [common_test.go] (https://github.com/liftbridge-io/go-liftbridge/blob/master/common_test.go), the `mockAPI` has not yet reflected this change in api, thus it will fail as well if pointing to latest commit. However, this is easy to fix, and also, it's up the client to fix it. 

But should we still keep this change while it has not yet been implemented on server side ?

**Comment by tylertreat** [comment]
Yeah, normally this isn't an issue since we point to a specific version, but since you're doing work around the API I see why this is an issue.

I have the server changes implemented, I just need to get it pushed up and merged. I will try to get that finished later today.

**Comment by LaPetiteSouris** [comment]
> Yeah, normally this isn't an issue since we point to a specific version, but since you're doing work around the API I see why this is an issue.
> 
> I have the server changes implemented, I just need to get it pushed up and merged. I will try to get that finished later today.

thanks. that would be really nice

**Comment by tylertreat** [comment]
@LaPetiteSouris It's taking a bit longer than I anticipated to get async publish finished and merged, so I'm going to revert the API changes (https://github.com/liftbridge-io/liftbridge-api/pull/28) so that the stream-level config changes aren't blocked.

**Comment by LaPetiteSouris** [comment]
> @LaPetiteSouris It's taking a bit longer than I anticipated to get async publish finished and merged, so I'm going to revert the API changes (#28) so that the stream-level config changes aren't blocked.

Thanks. I will try to finish stream-level config on my side soon

**Pull request merged**
